
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS first_name text,
  ADD COLUMN IF NOT EXISTS last_name text,
  ADD COLUMN IF NOT EXISTS mobile_number text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS street_address text,
  ADD COLUMN IF NOT EXISTS province text,
  ADD COLUMN IF NOT EXISTS signed_up_by text,
  ADD COLUMN IF NOT EXISTS terms_agreed boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS business_name text,
  ADD COLUMN IF NOT EXISTS industry text,
  ADD COLUMN IF NOT EXISTS years_in_business text,
  ADD COLUMN IF NOT EXISTS number_of_employees text,
  ADD COLUMN IF NOT EXISTS business_city text,
  ADD COLUMN IF NOT EXISTS business_address text,
  ADD COLUMN IF NOT EXISTS business_province text,
  ADD COLUMN IF NOT EXISTS twelve_month_goal text,
  ADD COLUMN IF NOT EXISTS biggest_challenge text,
  ADD COLUMN IF NOT EXISTS founder_inspiration text,
  ADD COLUMN IF NOT EXISTS competitor_envy text,
  ADD COLUMN IF NOT EXISTS monthly_revenue_range text,
  ADD COLUMN IF NOT EXISTS new_customers_target text,
  ADD COLUMN IF NOT EXISTS urgency_level text,
  ADD COLUMN IF NOT EXISTS current_marketing_assets text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS agency_history text,
  ADD COLUMN IF NOT EXISTS monthly_marketing_budget text,
  ADD COLUMN IF NOT EXISTS preferred_contact_channels text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS best_call_time text,
  ADD COLUMN IF NOT EXISTS wants_consultation_call boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS wants_personalized_proposal boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS popia_consent boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS onboarding_step smallint DEFAULT 1;
